# Generated by Django 5.1.6 on 2025-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favoritebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='book_key',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
