# Generated by Django 5.1.6 on 2025-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='review',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
