# Generated by Django 5.1.6 on 2025-03-21 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_favoritebook_review_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
