# Generated by Django 5.1.6 on 2025-04-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_wishlistbook_alter_favoritebook_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='register_date',
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
