# Generated by Django 5.1.6 on 2025-04-11 17:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_book_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, default=api.models.default_profile_picture, max_length=500, null=True),
        ),
    ]
